on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

name: Create Tag

jobs:
  tag:
    name: "New Tag"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: tag-version
        id: version
        uses: juliansangillo/tag-version@v1
        with:
          production-branch: main