name: Auto.Tag

on:
  - push

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@main
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: phish108/autotag-action@v1.1.55
        name: Auto Tag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          tag_prefix: "v"
          version: "${{ steps.previous_step.outputs.version }}"
