on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    types:
      - closed

permissions:
  contents: write

name: Create Release

jobs:
  tagged-release:
    if: github.event.pull_request.merged == true
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt