name: Auto.Tag

on:
  - push

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12
          - 21.x
    steps:
      - uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          release-branch: "main"
          issue-labels: "enhancement"
