on:
  push

permissions:
  contents: write

name: Create Tag

jobs:
  tag:
    name: "New Tag"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: tag-version
        id: version
        uses: juliansangillo/tag-version@v1
        with:
          production-branch: main