name: Auto.Tag

on:
  - push

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: phish108/autotag-action@v1.1.55
        name: Auto Tag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}